# 开发环境配置
# 这里的配置会覆盖default.toml中的同名配置

[server]
host = "127.0.0.1"
port = 8080
secret_key = "super_secure_key_for_development_only"
 
[database]
url = "postgres://kawaaanime@localhost/lycrex_auth" 

[cors]
allowed_origins = [
    "http://localhost:8080",
    "http://127.0.0.1:8080"
] 

[log]
level = "debug"
format = "pretty"

[security]
# 开发环境使用较短的令牌生命周期方便测试
access_token_lifetime = 1800 