# 测试环境配置
# 测试环境使用内存数据库和测试专用配置

[server]
host = "127.0.0.1"
port = 8080
secret_key = "测试环境密钥"

[database]
url = "postgres://kawaaanime@localhost/lycrex_auth_test"

[log]
level = "debug"
format = "default"

[security]
# 测试环境使用较短的令牌生命周期
access_token_lifetime = 60
refresh_token_lifetime = 1
authorization_code_lifetime = 60

[admin]
# 测试环境管理员密码
password = "test123" 