name: 自动部署与服务控制

# 设置权限
permissions:
  contents: read
  packages: read

on:
  push:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    environment: server-hk0
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v3
      with:
        submodules: false
        
    - name: 配置Git凭据并检出子模块
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config --global url."https://${GH_PAT}@github.com/".insteadOf "https://github.com/"
        
        if [ -f ".gitmodules" ]; then
          git submodule sync
          git submodule update --init --recursive
          git submodule status
        else
          echo "没有发现子模块配置，跳过子模块处理"
        fi
    
    - name: 安装Rust工具链
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    
    - name: 构建应用
      run: |
        cargo build --release
        
        if [ -f "target/release/lycrex-auth" ]; then
          echo "PKG_NAME=lycrex-auth" >> $GITHUB_ENV
          file target/release/lycrex-auth
        else
          EXECUTABLE=$(find target -type f -executable -name "lycrex-auth" | head -n 1)
          if [ -n "$EXECUTABLE" ]; then
            mkdir -p target/release/
            cp "$EXECUTABLE" "target/release/lycrex-auth"
            echo "PKG_NAME=lycrex-auth" >> $GITHUB_ENV
          else
            echo "错误: 无法找到可执行文件"
            exit 1
          fi
        fi
    
    - name: 检查服务器配置
      run: |
        if [ -z "${{ vars.SERVER_HOST }}" ] || [ -z "${{ secrets.SERVER_USERNAME }}" ] || 
           [ -z "${{ vars.DEPLOY_PATH }}" ] || [ -z "${{ vars.SERVICE_NAME }}" ]; then
          echo "错误: 缺少必要的服务器配置"
          exit 1
        fi
      
    - name: 准备部署文件
      run: |
        mkdir -p deploy
        
        # 复制主应用程序
        cp target/release/${PKG_NAME} deploy/
        chmod +x deploy/${PKG_NAME}
        
        # 复制必要目录
        for dir in config migrations db scripts; do
          if [ -d "$dir" ]; then
            cp -r $dir deploy/
            [ "$dir" = "scripts" ] && chmod +x deploy/scripts/*.sh
          fi
        done
        
        # 处理静态文件
        if [ -d "src/static" ]; then
          mkdir -p deploy/static
          cp -r src/static/* deploy/static/
        else
          mkdir -p deploy/static
        fi
        
        touch deploy/.env
    
    - name: 部署到服务器
      uses: appleboy/ssh-action@master
      with:
        host: ${{ vars.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ vars.SERVER_PORT || 22 }}
        script: |
          # 检查服务是否存在并尝试停止，但使用if语句代替&&
          if sudo systemctl is-active --quiet ${{ vars.SERVICE_NAME }}; then
            sudo systemctl stop ${{ vars.SERVICE_NAME }}
          fi
          echo "服务已停止或不存在，继续部署"
          
          # 备份配置
          [ -f "${{ vars.DEPLOY_PATH }}/.env" ] && mkdir -p /tmp/backup && cp ${{ vars.DEPLOY_PATH }}/.env /tmp/backup/
          
          # 清空并准备目录
          mkdir -p ${{ vars.DEPLOY_PATH }}
          rm -rf ${{ vars.DEPLOY_PATH }}/*
          
          # 恢复配置
          [ -f "/tmp/backup/.env" ] && cp /tmp/backup/.env ${{ vars.DEPLOY_PATH }}/ && rm -rf /tmp/backup
    
    - name: 上传部署文件
      uses: appleboy/scp-action@master
      with:
        host: ${{ vars.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ vars.SERVER_PORT || 22 }}
        source: "deploy/*"
        target: "${{ vars.DEPLOY_PATH }}"
        strip_components: 1
        
    - name: 配置服务
      uses: appleboy/ssh-action@master
      with:
        host: ${{ vars.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ vars.SERVER_PORT || 22 }}
        script: |
          chmod +x ${{ vars.DEPLOY_PATH }}/${{ env.PKG_NAME }}
          
          # 初始化数据库
          if [ -f "${{ vars.DEPLOY_PATH }}/scripts/init_db.sh" ]; then
            cd ${{ vars.DEPLOY_PATH }}
            export POSTGRES_USER="${{ secrets.DB_USER || secrets.SERVER_USERNAME }}"
            export POSTGRES_PASSWORD="${{ secrets.DB_PASSWORD }}"
            export POSTGRES_HOST="${{ secrets.DB_HOST || 'localhost' }}"
            export POSTGRES_PORT="${{ secrets.DB_PORT || '5432' }}"
            export DB_NAME="${{ vars.DB_NAME || 'lycrex_auth' }}"
            
            bash scripts/init_db.sh || echo "数据库初始化可能已完成或出现错误"
          fi
          
          # 创建服务配置
          if ! sudo test -f /etc/systemd/system/${{ vars.SERVICE_NAME }}.service; then
            cat << EOF | sudo tee /etc/systemd/system/${{ vars.SERVICE_NAME }}.service
          [Unit]
          Description=Lycrex Auth Service
          After=network.target
          
          [Service]
          Type=simple
          User=${{ secrets.SERVER_USERNAME }}
          WorkingDirectory=${{ vars.DEPLOY_PATH }}
          ExecStart=${{ vars.DEPLOY_PATH }}/${{ env.PKG_NAME }}
          Restart=always
          RestartSec=5
          StandardOutput=journal
          StandardError=journal
          Environment="RUST_LOG=info,sqlx=off,sqlx::query=off"
          Environment="RUN_ENV=production"
          Environment="POSTGRES_USER=${{ secrets.DB_USER || secrets.SERVER_USERNAME }}"
          Environment="POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }}"
          Environment="POSTGRES_HOST=${{ secrets.DB_HOST || 'localhost' }}"
          Environment="POSTGRES_PORT="${{ secrets.DB_PORT || '5432' }}"
          Environment="DB_NAME=${{ vars.DB_NAME || 'lycrex_auth' }}"
          
          [Install]
          WantedBy=multi-user.target
          EOF
            
            sudo systemctl daemon-reload
          fi
          
          # 启动服务但不检查状态
          sudo systemctl enable ${{ vars.SERVICE_NAME }} || true
          sudo systemctl start ${{ vars.SERVICE_NAME }} || true
          echo "Lycrex Auth Service 部署完成" 